# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=flake8

install:
  - pip install tox

script: tox
