# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=pypy3
  - TOX_ENV=flake8

install:
  - pip install -r requirements.txt
  - pip install tox

# command to run tests, e.g. python setup.py test
script: tox -e TOX_ENV
